apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stateless
  namespace: default
  labels:
    app: stateless
    env: prod
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - a765aa0061e5a4d7aa5d63e86a1083dd-1954319865.us-east-1.elb.amazonaws.com
    secretName: stateless-tls
  rules:
    - host: a765aa0061e5a4d7aa5d63e86a1083dd-1954319865.us-east-1.elb.amazonaws.com
      http:
        paths:
          - path: /stateless(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: stateless
                port:
                  number: 80
