apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: stateless
  namespace: default
  labels:
    app: stateless
    env: prod
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
    kubernetes.io/ingress.class: "nginx"
spec:
  tls:
  - hosts:
    - stateless.mrzacarias.com
    secretName: stateless-tls
  rules:
  - host: stateless.mrzacarias.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: stateless
            port:
              number: 80
