apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: stateless
  namespace: default
  labels:
    app: stateless
    env: prod
spec:
  maxUnavailable: 25%
  selector:
    matchLabels:
      app: stateless
      env: prod
