apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: stateless
  namespace: default
  labels:
    app: stateless
    env: prod
    release: prometheus-stack
spec:
  targetLabels: ['env','app']
  endpoints:
  - interval: 15s
    port: internal
    path: /metrics
  namespaceSelector:
    matchNames:
    - default
  selector:
    matchLabels:
      app: stateless
      env: prod
